[package]
name = "zk-guest-sp1-host"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cloak-zk"
path = "src/bin/cloak-zk.rs"

[[bin]]
name = "generate_examples"
path = "src/bin/generate_examples.rs"

[[bin]]
name = "get_vkey_hash"
path = "src/bin/get_vkey_hash.rs"

[[bin]]
name = "batch-prove"
path = "src/bin/batch-prove.rs"

[[bin]]
name = "generate-batch-example"
path = "src/bin/generate_batch_example.rs"

[lib]
name = "zk_guest_sp1_host"
path = "src/lib.rs"

[dependencies]
sp1-sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
base58 = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
rand = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
